spring.application.name=jpa-demo

# H2 in-memory DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=Hh13211792

# Go to http://localhost:8080/h2-console when the app is running

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA displays SQL to the console (debugging is very important!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Recreate the schema every time it runs (for developers only!)
spring.jpa.hibernate.ddl-auto=create-drop